version: "3.7"

services:
  nest-bp-app:
    hostname: nest-bp-app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app/nest-bp
      - /var/app/nest-bp/node_modules
    networks:
      - nest-bp-network
    depends_on:
      - nest-bp-postgres

  nest-bp-postgres:
    hostname: nest-bp-postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    networks:
      - nest-bp-network
    volumes:
      - nest-bp-postgres:/var/lib/postgresql/data

networks:
  nest-bp-network:
    driver: bridge
volumes:
  nest-bp-postgres: